### ISSUE TITLE
Endpoint needed 1 for the Matchminer Curation Interface

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/matchminer-curate#44]
For the current endpoint of "http://oncokb.org/api/v1/variants", provide a boolean option called "includeGeneralMutations". When this option is set to true, return the original oncokb variants plus the general mutations such as "Oncogenic Mutations", "Truncating Mutations" etc.

**Comment by zhx828** [comment]
The endpoint will be implemented under /classification/variants
