### ISSUE TITLE
Integrate MSK Discover API to enrich the trial import feature 

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/matchminer-curate#85]
Here is the API end point to use to get all trials info https://discover.mskcc.org:443/api/trials/

For MSK trials, use the discovery API return first(current_accrual and all other fields). If not found, use the clinical trials gov API return.

**Comment by victoria34** [comment]
Since MSK discover trials is going to be retired, do we still need to integrate this API?

**Comment by victoria34** [comment]
Implemented
